binutils:
	echo "Building Binutils"
	bash ./build-binutils.sh
gcc:
	echo "Building GCC"
	bash ./build-gcc.sh

all:
	echo "Building Binutils"
	bash ./build-binutils.sh
	echo "Building GCC"
	bash ./build-gcc.sh